"""Generate typed diagnostic variants from frozen native kernels, with provenance."""
import hashlib
import json
from pathlib import Path
import tarfile
import sys

r=Path(__file__).resolve().parents[1]
src=r/'sources/stiff_perf_v37/StiffGIPC'
dest=r/'sources/mas_replay_v38'
dest.mkdir(exist_ok=True)
def extract(text,name):
    start=text.index(name+'(')
    start=text.rfind('\n',0,start)+1
    # __forceinline__ functions are also declared on a single line.
    opening=text.index('{',start);depth=1;end=opening+1
    while depth:
        depth+=(text[end]=='{')-(text[end]=='}');end+=1
    return text[start:end]
mas=(src/'solver/MASPreconditioner.cu').read_text()
pcg=(src/'linear_system/solver/pcg_solver.cu').read_text()
parts=[extract(mas,n) for n in ['_LanemaskLt','_segmentInterval']]
parts.append('template<class Z>\n'+extract(mas,'__collectFinalZ_new').replace('Precision_T3','Z'))
inverse=extract(mas,'__inverse6_P96x96').replace('__GEIGEN__::MasMatrixSymf*','Mat*')
parts.append('template<class Mat>\n'+inverse)
aggregate=extract(mas,'__buildMultiLevelR_optimized_new')
aggregate=aggregate.replace('Eigen::Vector3f','Eigen::Matrix<S,3,1>').replace('FloatP','S').replace('float tmp','S tmp')
parts.append('template<class S>\n'+aggregate)
apply=extract(mas,'_schwarzLocalXSym6')
apply=apply.replace('__GEIGEN__::MasMatrixSymf','Mat').replace('const Eigen::Vector3f*','const Eigen::Matrix<R,3,1>*')
apply=apply.replace('Eigen::Vector3f','Eigen::Matrix<C,3,1>').replace('FloatP','C')
apply=apply.replace('Precision_T3','Z')
apply=apply.replace('= mR[vcid];','= mR[vcid].template cast<C>();')
apply=apply.replace('Pred[Hid].M[index].transpose()', 'Pred[Hid].M[index].template cast<C>().transpose()')
apply=apply.replace('Pred[Hid].M[index] *', 'Pred[Hid].M[index].template cast<C>() *')
parts.append('template<class Mat,class R,class C,class Z>\n'+apply)
parts.extend(extract(pcg,n) for n in ['PCG_vdv_Reduction','update_vector_dx_r','update_vector_c'])
header=dest/'native_kernels.cuh'
repair='--repair' in sys.argv
assert repair or not header.exists(), 'Use explicit pre-run build repair; original bundle is preserved'
header.write_text('// Generated by prepare_replay_v38.py from v37. Preserve upstream MPL provenance.\n'+'\n\n'.join(parts))
files=[p for p in dest.iterdir() if p.is_file()]+[Path(__file__)]
upstream=[p for p in src.rglob('*') if p.is_file()]
manifest={'scope':'Standalone diagnostic replay; frozen v37 upstream kernels/headers',
          'files':[{'path':p.relative_to(r).as_posix(),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in sorted(files+upstream)]}
suffix='_repaired' if repair else ''
mp=r/f'manifests/mas_replay_v38{suffix}.json';assert not mp.exists();mp.write_text(json.dumps(manifest,indent=2))
archive=r/f'bundles/mas_replay_v38{suffix}.tar.gz';assert not archive.exists()
with tarfile.open(archive,'w:gz') as t:
    for p in files+[mp]:t.add(p,arcname=p.relative_to(r).as_posix())
print(json.dumps({'archive':str(archive),'sha256':hashlib.sha256(archive.read_bytes()).hexdigest()}))
